image: Visual Studio 2017
version: 2.0.{build}
configuration: Release
install:
- set NUGET_VERSION=%APPVEYOR_BUILD_VERSION%
build_script:
- ps: .\build.ps1 -Target package
test:
  assemblies:
    - '**\*.Tests.dll'
artifacts:
- path: '**\bin\Release\*.nupkg'
  name: NuGet